[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "celfa"
version = "0.0.2"
authors = [
  { name="Daniel Schmid", email="daniel.ds.schmid@gmail.com" },
]
description = "X"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/s4294967296/cnn"
"Bug Tracker" = "https://github.com/s4294967296/cnn/issues"