[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "clippings2anki"
version = "0.2.1"
authors = [
  { name="bewu", email="bewu@bewu.dev" },
]
description = "clippings2anki"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "tqdm",
    "wiktionaryparser",
    "pyqt6"
]

[project.urls]
"Homepage" = "https://github.com/bewuwy/kindle-clippings-anki-exporter"
"Bug Tracker" = "https://github.com/bewuwy/kindle-clippings-anki-exporter/issues"
