[tool.poetry]
name = "ocp-project-plugin"
version = "0.0.0.0.278"
description = "Netbox OCP Project Plugin"
authors = [
    "Tim Rhomberg <timrhomberg@hotmail.com>",
]
readme = "README.md"
packages = [{include = "ocp_project_plugin"}]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"