[tool.poetry]
name = "gitflux"
version = "0.3.0"
description = "A command-line utility to help you manage repositories hosted on GitHub."
authors = ["HE Yaowen <he.yaowen@hotmail.com>"]
license = "GPL-3.0"
readme = "README.md"
packages = [{include = "gitflux", from="src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
click = "^8.1.3"
pygithub = "^1.57"

[tool.poetry.group.dev.dependencies]
chance = "^0.110"
poethepoet = "^0.18.1"
pre-commit = "^3.0.4"
pylint = "^2.16.2"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
pyinstaller = "^5.8.0"

[tool.poetry.scripts]
gitflux = "gitflux.__main__:cli"

[tool.poe.tasks]
init = {shell ="poetry install && poetry run pre-commit install"}
lint = "poetry run pylint src"
test = "poetry run pytest --cov=src --cov-report=term-missing"
dist = "poetry run pyinstaller gitflux.spec"
gitflux = "poetry run gitflux"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
