[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]

[tool.calcipy.test]
pythons = ["3.8"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.0"
version_files = ["pyproject.toml", "shoal/__init__.py"]

[tool.isort]
balanced_wrapping = true
default_section = "THIRDPARTY"
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = "shoal"
length_sort = false
line_length = 120
multi_line_output = 5

[tool.poetry]
name = "shoal"
version = "0.4.1"
description = "Lazy, Python-first, alternative to make, just, doit, and invoke"
license = "MIT"
authors = ["Kyle King <dev.act.kyle@gmail.com>"]
maintainers = []
repository = "https://github.com/kyleking/shoal"
documentation = "https://shoal.kyleking.me"
readme = "docs/README.md"
include = ["LICENSE.md"]
keywords = []
classifiers = [
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
] # https://pypi.org/classifiers/

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kyleking/shoal/issues"
"Changelog" = "https://github.com/kyleking/shoal/blob/main/docs/docs/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.7.12"
beartype = ">=0.12.0"
invoke = ">=2.0.0"
pydantic = ">=1.10.4"
rich = ">=13.3.1"

[tool.poetry.dev-dependencies]
# calcipy = { version = ">=0.21.3", extras = ["dev", "lint", "test"] }
