[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"

[project]
name = "atlantiscore"
version = "1.6.0"
description = "atlantiscore"
readme = "README.md"
authors = [{ name = "Atlantis Labs", email = "r00tail@protonmail.com" }]
dependencies = [
    "codercore ~= 1.8",
    "coincurve ~= 18.0",
    "eth-hash[pycryptodome]~=0.5",
    "eth-utils ~= 1.9",
    "sqlalchemy[asyncio] ~= 1.4",
]

[project.optional-dependencies]
test = [
    "pytest ~= 7.2.0",
    "pytest-asyncio ~= 0.20.1",
    "pytest-cov ~= 4.0.0",
    "pytest-mock ~= 3.10.0",
    "pytest-xdist[psutil] ~= 3.0.2",
]
dev = [
    "black ~= 22.10.0"
]

[tool.bumpver]
current_version = "1.6.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"'
]
