[build-system]
requires = ["setuptools","xlrd","openpyxl","pandas","PyPDF2","build","numpy","xlwt","jupyter","numexpr","openpyxl","bottleneck","xarray"]

build-backend = "setuptools.build_meta"
[project]
name = "alacorder"
version = "71.5.4.3"
authors = [
  { name="Sam Robson", email="sbrobson@crimson.ua.edu" },
]
description = "beta"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = ["setuptools","xlrd","openpyxl","pandas","PyPDF2","build","numpy","xlwt","jupyter","numexpr","openpyxl","bottleneck","xarray"]
