##############################################
#### Written By: SATYAKI DE               ####
#### Written On: 20-Dec-2019              ####
#### Modified On 20-Dec-2019              ####
####                                      ####
#### Objective: Main scripts for logging  ####
##############################################

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FastDataMask"
version = "0.0.5"
authors = [
  { name="Satyaki De", email="satyakide.us@gmail.com" },
]
description = "This is the main class that will generate masked data for light weight use cases."
readme = "README.md"
license = { file="license.txt" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/SatyakiDe2019/FastDataMask"
"Bug Tracker" = "https://github.com/SatyakiDe2019/FastDataMask/issues"

[tool.poetry]
exclude=['Scans','Template']
