[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "FAIRsoft"
version = "0.1.14"
authors = [
  { name="Eva Martin del Pico", email="eva.martin@bsc.es" },
]
description = "FAIRsoft package for the aggregation of Life Sciences software metadata and FAIR evaluation."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3"
]

[project.urls]
"Bug Tracker" = "https://gitlab.bsc.es/inb/elixir/software-observatory/FAIRsoft_ETL/issues"
"Repository" = "https://gitlab.bsc.es/inb/elixir/software-observatory/FAIRsoft_ETL/-/tree/master/FAIRsoft" 

[project.scripts]
FAIRsoft_transform = "FAIRsoft.transformation.cli:main"
FAIRsoft_integrate = "FAIRsoft.integration.cli:main"

[options] 
install_requires = [
    "bidict",
    "matplotlib",
    "munch",
    "pymongo",
    "requests",
    "selenium",
    "simplejson",
    "webdriver_manager",
    "bibtexparser"]